name: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.setter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            app:
              - '!.github/**'

      - name: Set outputs
        id: setter
        if: steps.changes.outputs.app == 'true'
        run: |
          echo "changes=true"  >> $GITHUB_OUTPUT

  cicd:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.changes == 'true'
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            app:
              - '!.github/**'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        id: build-and-push
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meme-giver:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/meme-giver:latest

      - name: Sign image with a key
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          echo $images
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS:  ${{ secrets.DOCKERHUB_USERNAME }}/meme-giver:latest ${{ secrets.DOCKERHUB_USERNAME }}/meme-giver:${{ github.sha }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}

      - name: Checkout manifest repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}
          repository: BoredOtter/meme-giver-deployment
          path: ./manifest
          ref: main

      - name: Setup Git
        working-directory: ./manifest
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url --push origin https://github.com/BoredOtter/meme-giver-deployment.git

      - name: Render manifest template
        working-directory: ./manifest
        run: |
          export TAG=${{ github.sha }}
          sed "s/__TAG__/$TAG/" manifest-template.yaml > deployment/manifest.yaml

      - name: Push updated manifest
        working-directory: ./manifest
        run: |
          git add .
          git commit -m "Updated image tag to: ${{ github.sha }}"
          git push