name: Build, Publish, and Sign Image

on:
  push:
    branches:
      - main

jobs:
  build-publish-sign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.3.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/meme-giver:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/meme-giver:latest

    - name: Sign image with a key
      run: |
        images=""
        for tag in ${TAGS}; do
          images+="${tag}@${DIGEST} "
        done
        cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
      env:
        TAGS: ${{ github.sha }} latest
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
