name: Trivy

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  security-events: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/boredotter/meme-giver:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/boredotter/meme-giver:${{ github.sha }}'
          template: '@/contrib/html.tpl'
          output: 'trivy-results.html'
          scan-type: 'image'
          vuln-type: 'library'

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-results.html